In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv('50_Startups.csv')[
    ['R&D Spend', 'Administration', 'Marketing Spend', 'Profit']
]

# Scale down values
df = df / 10000

# Round values
df = df.round(2)

# Random sample
np.random.seed(9)
df = df.sample(5).reset_index(drop=True)

print(df)

   R&D Spend  Administration  Marketing Spend  Profit
0       7.84           15.38            29.97   11.13
1       4.41            5.13            19.70    8.99
2      15.34           10.11            40.79   19.11
3      11.99           15.65            25.65   13.26
4       2.22           15.48             2.83    6.52

In [3]:
df = df.iloc[:,0:-1]
df

   R&D Spend  Administration  Marketing Spend
0       7.84           15.38            29.97
1       4.41            5.13            19.70
2      15.34           10.11            40.79
3      11.99           15.65            25.65
4       2.22           15.48             2.83

In [5]:
df.iloc[1, 0] = np.nan
df.iloc[3, 1] = np.nan
df.iloc[-1, -1] = np.nan

In [6]:
df.head()

   R&D Spend  Administration  Marketing Spend
0       7.84           15.38            29.97
1        NaN            5.13            19.70
2      15.34           10.11            40.79
3      11.99             NaN            25.65
4       2.22           15.48              NaN

In [7]:

df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [8]:
df0

   R&D Spend  Administration  Marketing Spend
0     7.8400          15.380          29.9700
1     9.3475           5.130          19.7000
2    15.3400          10.110          40.7900
3    11.9900          11.525          25.6500
4     2.2200          15.480          29.0275

In [10]:
# Remove the col1 imputed value
df1 = df0.copy()

df1.iloc[1, 0] = np.nan

df1

   R&D Spend  Administration  Marketing Spend
0       7.84          15.380          29.9700
1        NaN           5.130          19.7000
2      15.34          10.110          40.7900
3      11.99          11.525          25.6500
4       2.22          15.480          29.0275

In [11]:
X = df1.iloc[[0,2,3,4],1:3]
X

   Administration  Marketing Spend
0          15.380          29.9700
2          10.110          40.7900
3          11.525          25.6500
4          15.480          29.0275

In [12]:
y = df1.iloc[[0,2,3,4],0]
y

0     7.84
2    15.34
3    11.99
4     2.22
Name: R&D Spend, dtype: float64

In [16]:

lr = LinearRegression()

lr.fit(X, y)

lr.predict(df1.iloc[1, 1:].values.reshape(1, 2))

d:\ml\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([22.99402644])

In [17]:
df1.iloc[1,0] = 23.14

In [18]:
df1

   R&D Spend  Administration  Marketing Spend
0       7.84          15.380          29.9700
1      23.14           5.130          19.7000
2      15.34          10.110          40.7900
3      11.99          11.525          25.6500
4       2.22          15.480          29.0275

In [19]:
df1.iloc[3, 1] = np.nan

df1

   R&D Spend  Administration  Marketing Spend
0       7.84           15.38          29.9700
1      23.14            5.13          19.7000
2      15.34           10.11          40.7900
3      11.99             NaN          25.6500
4       2.22           15.48          29.0275

In [20]:
X = df1.iloc[[0,1,2,4],[0,2]]
X

   R&D Spend  Marketing Spend
0       7.84          29.9700
1      23.14          19.7000
2      15.34          40.7900
4       2.22          29.0275

In [21]:
y = df1.iloc[[0,1,2,4],1]
y

0    15.38
1     5.13
2    10.11
4    15.48
Name: Administration, dtype: float64

In [22]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

d:\ml\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.38638278])

In [23]:
df1.iloc[3,1] = 11.06

In [24]:
df1

   R&D Spend  Administration  Marketing Spend
0       7.84           15.38          29.9700
1      23.14            5.13          19.7000
2      15.34           10.11          40.7900
3      11.99           11.06          25.6500
4       2.22           15.48          29.0275

In [26]:
df1.iloc[4, -1] = np.nan

df1

   R&D Spend  Administration  Marketing Spend
0       7.84           15.38            29.97
1      23.14            5.13            19.70
2      15.34           10.11            40.79
3      11.99           11.06            25.65
4       2.22           15.48              NaN

In [27]:
X = df1.iloc[0:4,0:2]
X

   R&D Spend  Administration
0       7.84           15.38
1      23.14            5.13
2      15.34           10.11
3      11.99           11.06

In [28]:
y = df1.iloc[0:4,-1]
y

0    29.97
1    19.70
2    40.79
3    25.65
Name: Marketing Spend, dtype: float64

In [29]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

d:\ml\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([27.54937963])

In [30]:
df1.iloc[4,-1] = 31.56

In [31]:
df1

   R&D Spend  Administration  Marketing Spend
0       7.84           15.38            29.97
1      23.14            5.13            19.70
2      15.34           10.11            40.79
3      11.99           11.06            25.65
4       2.22           15.48            31.56

In [32]:

# Subtract 0th iteration from 1st iteration

df1 - df0

   R&D Spend  Administration  Marketing Spend
0     0.0000           0.000           0.0000
1    13.7925           0.000           0.0000
2     0.0000           0.000           0.0000
3     0.0000          -0.465           0.0000
4     0.0000           0.000           2.5325

In [33]:

df2 = df1.copy()

df2.iloc[1,0] =  np.nan

df2

   R&D Spend  Administration  Marketing Spend
0       7.84           15.38            29.97
1        NaN            5.13            19.70
2      15.34           10.11            40.79
3      11.99           11.06            25.65
4       2.22           15.48            31.56

In [34]:
X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

d:\ml\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([22.45496431])

In [35]:
df2.iloc[1,0] = 23.78

In [36]:
df2.iloc[3,1] =  np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

d:\ml\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.5528158])

In [37]:
df2.iloc[3,1] = 11.22

In [38]:
df2.iloc[4,-1] =  np.nan

X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

d:\ml\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([32.21393014])

In [39]:
df2.iloc[4,-1] = 31.56

In [40]:
df2

   R&D Spend  Administration  Marketing Spend
0       7.84           15.38            29.97
1      23.78            5.13            19.70
2      15.34           10.11            40.79
3      11.99           11.22            25.65
4       2.22           15.48            31.56

In [41]:

df2 - df1

   R&D Spend  Administration  Marketing Spend
0       0.00            0.00              0.0
1       0.64            0.00              0.0
2       0.00            0.00              0.0
3       0.00            0.16              0.0
4       0.00            0.00              0.0

In [43]:

df3 = df2.copy()

df3.iloc[1,0] =  np.nan

df3

   R&D Spend  Administration  Marketing Spend
0       7.84           15.38            29.97
1        NaN            5.13            19.70
2      15.34           10.11            40.79
3      11.99           11.22            25.65
4       2.22           15.48            31.56

In [44]:
X = df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

d:\ml\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([23.13978658])

In [45]:
df3.iloc[1,0] = 24.57

In [46]:
df3.iloc[3,1] =  np.nan
X = df3.iloc[[0,1,2,4],[0,2]]
y = df3.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

d:\ml\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.71457854])

In [47]:
df3.iloc[3,1] = 11.37

In [48]:
df3.iloc[4,-1] =  np.nan

X = df3.iloc[0:4,0:2]
y = df3.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[4,0:2].values.reshape(1,2))

d:\ml\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([37.33904485])

In [49]:
df3.iloc[4,-1] = 45.53

In [50]:
df2.iloc[3,1] = 11.22

In [51]:
df3

   R&D Spend  Administration  Marketing Spend
0       7.84           15.38            29.97
1      24.57            5.13            19.70
2      15.34           10.11            40.79
3      11.99           11.37            25.65
4       2.22           15.48            45.53

In [52]:
df3 - df2

   R&D Spend  Administration  Marketing Spend
0       0.00            0.00             0.00
1       0.79            0.00             0.00
2       0.00            0.00             0.00
3       0.00            0.15             0.00
4       0.00            0.00            13.97