In [1]:
import pandas as pd
import requests

In [2]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [10]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [11]:
temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,37.6171,8.715,29789
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,41.4528,8.688,22494
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,19.7460,8.572,13613
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,16.4514,8.566,17140
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,12.3315,8.556,9762

In [7]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
import time
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
session = requests.Session()
retries = Retry(total=5, backoff_factor=1,
                status_forcelist=[429, 500, 502, 503, 504])
session.mount('https://', HTTPAdapter(max_retries=retries))

frames = []
for i in range(1, 429):
    try:
        url = f'https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={i}'
        response = session.get(url, timeout=10)
        response.raise_for_status()
        data = response.json().get('results', [])
        temp_df = pd.DataFrame(data)[['id','title','overview','release_date','popularity','vote_average','vote_count']]
        frames.append(temp_df)
    except Exception as exc:
        print(f'page {i} failed: {exc}, retrying after delay')
        time.sleep(5)
        continue
if frames:
    df = pd.concat(frames, ignore_index=True)
else:
    df = pd.DataFrame()

In [14]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,37.6171,8.715,29789
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,41.4528,8.688,22494
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,19.7460,8.572,13613
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,16.4514,8.566,17140
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,12.3315,8.556,9762
...,...,...,...,...,...,...,...
8555,823999,Diabolik: Ginko Attacks!,Diabolik narrowly escapes Inspector Ginko's la...,2022-11-17,0.8689,5.979,485
8556,60405,Sharpay's Fabulous Adventure,After a talent scout spots her performing with...,2011-04-19,1.3306,6.000,557
8557,14451,Dead Snow,Eight medical students on a ski trip to Norway...,2009-01-09,3.4167,5.979,1204
8558,9453,Caligula,After the death of the paranoid emperor Tiberi...,1979-08-14,7.1524,5.979,956
8559,521007,Superintelligence,When an all-powerful Superintelligence chooses...,2020-12-11,3.5849,5.978,314

In [15]:
df.shape

(8560, 7)

In [17]:
df.to_csv('movies.csv')